require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompetenciesController do

  # This should return the minimal set of attributes required to create a valid
  # Competency. As you add validations to Competency, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CompetenciesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all competencies as @competencies" do
      competency = Competency.create! valid_attributes
      get :index, {}, valid_session
      assigns(:competencies).should eq([competency])
    end
  end

  describe "GET show" do
    it "assigns the requested competency as @competency" do
      competency = Competency.create! valid_attributes
      get :show, {:id => competency.to_param}, valid_session
      assigns(:competency).should eq(competency)
    end
  end

  describe "GET new" do
    it "assigns a new competency as @competency" do
      get :new, {}, valid_session
      assigns(:competency).should be_a_new(Competency)
    end
  end

  describe "GET edit" do
    it "assigns the requested competency as @competency" do
      competency = Competency.create! valid_attributes
      get :edit, {:id => competency.to_param}, valid_session
      assigns(:competency).should eq(competency)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Competency" do
        expect {
          post :create, {:competency => valid_attributes}, valid_session
        }.to change(Competency, :count).by(1)
      end

      it "assigns a newly created competency as @competency" do
        post :create, {:competency => valid_attributes}, valid_session
        assigns(:competency).should be_a(Competency)
        assigns(:competency).should be_persisted
      end

      it "redirects to the created competency" do
        post :create, {:competency => valid_attributes}, valid_session
        response.should redirect_to(Competency.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved competency as @competency" do
        # Trigger the behavior that occurs when invalid params are submitted
        Competency.any_instance.stub(:save).and_return(false)
        post :create, {:competency => {}}, valid_session
        assigns(:competency).should be_a_new(Competency)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Competency.any_instance.stub(:save).and_return(false)
        post :create, {:competency => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested competency" do
        competency = Competency.create! valid_attributes
        # Assuming there are no other competencies in the database, this
        # specifies that the Competency created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Competency.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => competency.to_param, :competency => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested competency as @competency" do
        competency = Competency.create! valid_attributes
        put :update, {:id => competency.to_param, :competency => valid_attributes}, valid_session
        assigns(:competency).should eq(competency)
      end

      it "redirects to the competency" do
        competency = Competency.create! valid_attributes
        put :update, {:id => competency.to_param, :competency => valid_attributes}, valid_session
        response.should redirect_to(competency)
      end
    end

    describe "with invalid params" do
      it "assigns the competency as @competency" do
        competency = Competency.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Competency.any_instance.stub(:save).and_return(false)
        put :update, {:id => competency.to_param, :competency => {}}, valid_session
        assigns(:competency).should eq(competency)
      end

      it "re-renders the 'edit' template" do
        competency = Competency.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Competency.any_instance.stub(:save).and_return(false)
        put :update, {:id => competency.to_param, :competency => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested competency" do
      competency = Competency.create! valid_attributes
      expect {
        delete :destroy, {:id => competency.to_param}, valid_session
      }.to change(Competency, :count).by(-1)
    end

    it "redirects to the competencies list" do
      competency = Competency.create! valid_attributes
      delete :destroy, {:id => competency.to_param}, valid_session
      response.should redirect_to(competencies_url)
    end
  end

end
